controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Nelmio API Documentation routes
nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.php'
    prefix: /api/doc
